In [11]:
import pandas as pd

# Read the CSV file
df_snp_dld_2024_rents = pd.read_csv('/home/noaman/Desktop/smart bricks/SB-Case Study Materials/data/snp_dld_2024_rents.csv')
df_snp_dld_2024_transaction = pd.read_csv('/home/noaman/Desktop/smart bricks/SB-Case Study Materials/data/snp_dld_2024_transactions.csv')

/tmp/ipykernel_21873/3598964011.py:4: DtypeWarning: Columns (35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_snp_dld_2024_rents = pd.read_csv('/home/noaman/Desktop/smart bricks/SB-Case Study Materials/data/snp_dld_2024_rents.csv')

In [ ]:
df_snp_dld_2024_rents.head()

,ejari_contract_number,registration_date,contract_start_date,contract_end_date,version_number,version_text,contract_amount,annual_amount,is_freehold,is_freehold_text,...,nearest_mall_en,nearest_mall_ar,master_project_en,master_project_ar,ejari_property_type_id,ejari_property_sub_type_id,req_from,req_to,entry_id,meta_ts
0,120130625001365,2024-01-24 11:14:33,2024-01-01,2024-12-31,12,Renewed,58000.0,58000.0,f,Non Free Hold,...,City Centre Mirdif,سيتي سنتر مردف,NaN,NaN,0,0,2024-01-01,2024-01-31,94368,2024-09-26 11:18:46.859
1,120130626005726,2024-01-09 16:48:47,2024-03-18,2025-03-17,12,Renewed,88000.0,88000.0,t,Free Hold,...,City Centre Mirdif,سيتي سنتر مردف,NaN,NaN,0,0,2024-01-01,2024-01-31,94368,2024-09-26 11:18:46.859
2,120130626007829,2024-01-16 11:39:26,2024-01-01,2024-12-31,12,Renewed,94000.0,94000.0,f,Non Free Hold,...,Dubai Mall,مول دبي,NaN,NaN,0,0,2024-01-01,2024-01-31,94368,2024-09-26 11:18:46.859
3,120130627008661,2024-01-15 18:28:05,2024-01-01,2024-12-31,12,Renewed,66000.0,66000.0,f,Non Free Hold,...,Mall of the Emirates,مول الإمارات,NaN,NaN,0,0,2024-01-01,2024-01-31,94368,2024-09-26 11:18:46.859
4,120130627009439,2024-01-22 13:34:29,2024-01-01,2024-12-31,12,Renewed,31200.0,31200.0,f,Non Free Hold,...,City Centre Mirdif,سيتي سنتر مردف,NaN,NaN,0,0,2024-01-01,2024-01-31,94368,2024-09-26 11:18:46.859

In [13]:
df_snp_dld_2024_transaction.head()

,transaction_number,transaction_datetime,transaction_type_en,transaction_type_id,transaction_subtype_en,transaction_subtype_id,registration_type_en,is_freehold_text,property_usage_en,property_usage_id,...,nearest_metro_en,nearest_metro_ar,nearest_mall_en,nearest_mall_ar,master_project_en,master_project_ar,req_from,req_to,entry_id,meta_ts
0,102-10-2024,2024-01-11 11:05:38,Sales,1,Sell - Pre registration,0,Off-Plan,Free Hold,Residential,1,...,Dubai Internet City,مدينة دبي للإنترنت,Mall of the Emirates,مول الإمارات,NaN,NaN,2024-01-01,2024-01-31,94359,2024-09-26 09:45:23.369
1,102-1000-2024,2024-01-08 18:00:51,Sales,1,Sell - Pre registration,0,Off-Plan,Free Hold,Residential,1,...,Nakheel Metro Station,محطة مترو النخيل,Marina Mall,مارينا مول,NaN,NaN,2024-01-01,2024-01-31,94359,2024-09-26 09:45:23.369
2,102-1001-2024,2024-01-08 18:00:57,Sales,1,Sell - Pre registration,0,Off-Plan,Non Free Hold,Residential,1,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,2024-01-31,94359,2024-09-26 09:45:23.369
3,102-1002-2024,2024-01-08 18:01:03,Sales,1,Sell - Pre registration,0,Off-Plan,Free Hold,Residential,1,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,2024-01-31,94359,2024-09-26 09:45:23.369
4,102-1003-2024,2024-01-08 18:01:07,Sales,1,Sell - Pre registration,0,Off-Plan,Free Hold,Residential,1,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,2024-01-31,94359,2024-09-26 09:45:23.369

In [17]:
print(df_snp_dld_2024_rents.isnull().sum())
print(df_snp_dld_2024_transaction.isnull().sum())

ejari_contract_number              0
registration_date                  0
contract_start_date                0
contract_end_date                  0
version_number                     0
version_text                       0
contract_amount                    0
annual_amount                     14
is_freehold                        0
is_freehold_text                   0
property_size_sqm                  0
parcel_id                     230425
property_id                        0
land_property_id                   0
property_type_en                   0
property_type_ar                   0
property_subtype_en             2545
property_subtype_ar             2545
property_usage_en               2844
property_usage_ar               2844
property_usage_id                  0
total_properties                   0
rooms                         721746
parking                       731686
project_name_en               576935
project_name_ar               576935
area_en                            0
area_ar                            0
area_id                            0
nearest_landmark_en            56810
nearest_landmark_ar            56810
nearest_metro_en              110681
nearest_metro_ar              110681
nearest_mall_en               120826
nearest_mall_ar               120826
master_project_en             747311
master_project_ar             747311
ejari_property_type_id             0
ejari_property_sub_type_id         0
req_from                           0
req_to                             0
entry_id                           0
meta_ts                            0
dtype: int64
transaction_number             0
transaction_datetime           0
transaction_type_en            0
transaction_type_id            0
transaction_subtype_en         0
transaction_subtype_id         0
registration_type_en           0
is_freehold_text               0
property_usage_en              0
property_usage_id              0
amount                         0
total_buyer                    0
total_seller                   0
transaction_size_sqm         660
property_size_sqm              0
parcel_id                 102355
property_id                    0
is_offplan                     0
is_freehold                  684
property_type_en               0
property_type_ar               0
property_type_id               0
property_subtype_en         1392
property_subtype_ar         1392
property_subtype_id            0
building_age                   0
rooms_en                   23257
rooms_ar                   21362
parking                    40463
project_name_en            24760
project_name_ar            24760
area_en                        0
area_ar                        0
area_id                        0
nearest_landmark_en        47412
nearest_landmark_ar        47412
nearest_metro_en           65982
nearest_metro_ar           65982
nearest_mall_en            66842
nearest_mall_ar            66842
master_project_en         162460
master_project_ar         162460
req_from                       0
req_to                         0
entry_id                       0
meta_ts                        0
dtype: int64

In [14]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [15]:
def load_data():
    rents =  pd.read_csv('../data/snp_dld_2024_rents.csv')
    transactions =  pd.read_csv('../data/snp_dld_2024_transactions.csv')
    return rents, transactions

In [53]:
def handle_missing_data(df):
    # Fill categorical missing values with "Unknown"
    categorical_cols = df.select_dtypes(include=["object"]).columns
    df[categorical_cols] = df[categorical_cols].fillna("Unknown")

    # Fill numerical missing values with median
    numerical_cols = df.select_dtypes(include=["number"]).columns
    imputer = SimpleImputer(strategy="median")
    df[numerical_cols] = imputer.fit_transform(df[numerical_cols])

    return df
def feature_engineering(df_rents):
    # Add contract duration in days
    df_rents["contract_duration"] = (
        pd.to_datetime(df_rents["contract_end_date"]) - pd.to_datetime(df_rents["contract_start_date"])
    ).dt.days

 
    return df_rents

def encode_categorical_with_frequency(df):
    categorical_cols = df.select_dtypes(include=["object"]).columns
    for col in categorical_cols:
        freq_map = df[col].value_counts().to_dict()
        df[col] = df[col].map(freq_map)
    return df

def scale_numerical(df):
    numerical_cols = df.select_dtypes(include=["number"]).columns
    scaler = StandardScaler()
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
    return df


def load_data(data_path):
    rents =  pd.read_csv('../data/snp_dld_2024_rents.csv')
    return rents 
def preprocess_data(data_path):
    rents = load_data(data_path)

    # Handle missing data
    rents = handle_missing_data(rents)
 
    # Perform feature engineering
    rents = feature_engineering(rents)

    # Encode categorical variables
    rents = encode_categorical_with_frequency(rents)
 
    # Scale numerical features
    rents = scale_numerical(rents)
 
    return rents
raw_data_path='../data/snp_dld_2024_rents.csv'

preprocess_data=preprocess_data(raw_data_path)
def save_data(rents):
    rents.to_csv("../data/dataset.csv", index=False)
 
    
save_data(preprocess_data)

/tmp/ipykernel_21873/3363567126.py:36: DtypeWarning: Columns (35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  rents =  pd.read_csv('../data/snp_dld_2024_rents.csv')

In [ ]:
def handle_missing_data(df):
    # Fill categorical missing values with "Unknown"
    categorical_cols = df.select_dtypes(include=["object"]).columns
    df[categorical_cols] = df[categorical_cols].fillna("Unknown")

    # Fill numerical missing values with median
    numerical_cols = df.select_dtypes(include=["number"]).columns
    imputer = SimpleImputer(strategy="median")
    df[numerical_cols] = imputer.fit_transform(df[numerical_cols])

    return df

In [52]:
def feature_engineering(df_rents):
    # Add contract duration in days
    df_rents["contract_duration"] = (
        pd.to_datetime(df_rents["contract_end_date"]) - pd.to_datetime(df_rents["contract_start_date"])
    ).dt.days

 
    return df_rents

In [39]:
from sklearn.preprocessing import OneHotEncoder

def encode_categorical_with_frequency(df):
    categorical_cols = df.select_dtypes(include=["object"]).columns
    for col in categorical_cols:
        freq_map = df[col].value_counts().to_dict()
        df[col] = df[col].map(freq_map)
    return df

def encode_categorical(df):
    categorical_cols = df.select_dtypes(include=["object"]).columns

    # OneHotEncode categorical columns
    encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
    encoded_data = pd.DataFrame(
        encoder.fit_transform(df[categorical_cols]),
        columns=encoder.get_feature_names_out(categorical_cols),
    )

    # Drop original categorical columns and merge encoded
    df = df.drop(categorical_cols, axis=1)
    df = pd.concat([df.reset_index(drop=True), encoded_data.reset_index(drop=True)], axis=1)

    return df

In [29]:
def scale_numerical(df):
    numerical_cols = df.select_dtypes(include=["number"]).columns
    scaler = StandardScaler()
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
    return df

In [ ]:
def preprocess_data():
    rents = load_data()

    # Handle missing data
    rents = handle_missing_data(rents)
 
    # Perform feature engineering
    rents = feature_engineering(rents)

    # Encode categorical variables
    rents = encode_categorical_with_frequency(rents)
 
    # Scale numerical features
    rents = scale_numerical(rents)
 
    return rents

In [46]:
rents, transactions = preprocess_data()

/tmp/ipykernel_21873/2965744327.py:2: DtypeWarning: Columns (35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  rents =  pd.read_csv('../data/snp_dld_2024_rents.csv')

In [51]:
transactions.columns

Index(['transaction_number', 'transaction_datetime', 'transaction_type_en',
       'transaction_type_id', 'transaction_subtype_en',
       'transaction_subtype_id', 'registration_type_en', 'is_freehold_text',
       'property_usage_en', 'property_usage_id', 'amount', 'total_buyer',
       'total_seller', 'transaction_size_sqm', 'property_size_sqm',
       'parcel_id', 'property_id', 'is_offplan', 'is_freehold',
       'property_type_en', 'property_type_ar', 'property_type_id',
       'property_subtype_en', 'property_subtype_ar', 'property_subtype_id',
       'building_age', 'rooms_en', 'rooms_ar', 'parking', 'project_name_en',
       'project_name_ar', 'area_en', 'area_ar', 'area_id',
       'nearest_landmark_en', 'nearest_landmark_ar', 'nearest_metro_en',
       'nearest_metro_ar', 'nearest_mall_en', 'nearest_mall_ar',
       'master_project_en', 'master_project_ar', 'req_from', 'req_to',
       'entry_id', 'meta_ts', 'is_large_transaction'],
      dtype='object')

In [49]:
def save_data(rents, transactions):
    rents.to_csv("../data/processed_rents.csv", index=False)
    transactions.to_csv("../data/processed_transactions.csv", index=False)
 
    
save_data(rents, transactions)